export interface ColaboradorFiltro {
    loginName: string;
    name: string;
    company: number;
    costCenter: string;
    department: number;
    location: string;
    category: number;
    manager: string;
    cpf: string;
    statusType: string;
}

export interface ColaboradorElement {
    id: number;
    name: string;
    lastName: string;
    cpf: string;
    motherName: string;
    fatherName: string;
    rgNumber: string;
    rgType: string;
    rgAuthority: string;
    rgEmissionDate: Date;
    birthdate: Date;
    registrationNumber: string;
    admissionDate: Date;
    dismissionDate: Date;
    disconnectionDate: Date;
    cellPhone: string;
    workPhone: string;
    residentialPhone: string;
    email: string;
    statusType: number;
    statusCode: string;
    statusDate: Date;
    category: number;
    costCenter: string;
    costCenterId: number;
    source: string;
    creationDate: Date;
    fullName: string;
    company: number;
    companyName: string;
    department: number;
    departmentName: string;
    departmentId: number;
    login: number;
    loginName: string;
    manager: string;
    registration: number;
    registrationName: string;
    registrationLogin: string;
    consultant: true;
    lastUpdate: Date;
    location: string;
    canLock: true;
    canUse: true;
    role: string;
    changeforEmployer: true
}